### ISSUE TITLE
Readme for output.tar files

### ISSUE THREAD

**Issue by abaheti95** [my89/co-squac#3]
Hi I am a bit confused as what each file mean in output.tar.
For example what does `quacftcoqa_coqa.coqa` mean. More specifically I am looking for quac model's output on coqa. Thanks in advance.

**Comment by my89** [comment]
Hi,

Sorry the naming is a bit hair brained. I think whats after the "_" doesn't matter.  "quacftcoqa" is pretrain quac, fine-tune coqa. I don't think I posted the output of quac and direct eval on coqa, but you can download any existing model and try it on the converted coqa data.

Best,
Mark
