### ISSUE TITLE
Question: why this string 'CANNOTANSWER' is added to every context field?

### ISSUE THREAD

**Issue by hohoCode** [my89/co-squac#4]
Question: 

why this string 'CANNOTANSWER' is added to every "context" field in the converted datasets (SQUAD 2/COQA/QUAC)? In original datasets this 'CANNOTANSWER' is not there.

For example,
"context": "The Normans ... 11th centuries gave their name to Normandy, a region in France. They were descended from  ... and it continued to evolve over the succeeding centuries. CANNOTANSWER","

Any special meaning by adding this into the important context field?

Thanks.

**Comment by my89** [comment]
Hi, 

Its just a simple way to encode "no-answer" that most of the methods use. When there is no answer, the "extracted" answer is that last token. Its not part of the original text. The evaluation scripts also expect to see that token when there is no answer.

I hope this helps,
Mark

**Comment by hohoCode** [comment]
Thanks. In Squad 2.0, it seems often that without modifications of the input 'context' field, people use the special added token '[CLS]' as 'NO ANSWER' (start/end position 0/0 for tokenized context field). I asked because this changed inputs somehow.. But now I got the idea. Thanks.
